internal/bminventory/inventory.go
```
kubectl logs bm-inventory-64f67ffbf6-sl25d | grep execute-e6eedab1
time="2020-04-05T08:42:45Z" level=info msg="Added new debug command <execute-e6eedab1> for cluster <d215504a-5b42-4548-9210-58d3f0fd4573> host <be745563-0f6a-42d5-bc0a-398511445282>: <echo hello>"
time="2020-04-05T08:42:45Z" level=info msg="Submitting step <execute-e6eedab1> to cluster <d215504a-5b42-4548-9210-58d3f0fd4573> host <be745563-0f6a-42d5-bc0a-398511445282> Command: <bash> Arguments: <[-c echo hello]>"
time="2020-04-05T08:42:45Z" level=info msg="Received step reply <execute-e6eedab1> from cluster <d215504a-5b42-4548-9210-58d3f0fd4573> host <be745563-0f6a-42d5-bc0a-398511445282>  exit-code <0> stdout <hello> stderr <>"
```
=> Log debug step-id when setting the command

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
It's not easy validating it in UT.
=> Use the proxy parameters when generation the ISO

internal/bminventory/inventory.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host.go, internal/host/mock_host_api.go, subsystem/cluster_test.go
This reverts commit 4149e2c731cbf602a2551d2d8c69efa6f9574d3e.
=> MGMT-705 Choose boot device for the installation, taking first one

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/common.go, internal/cluster/error.go, internal/cluster/installed.go, internal/cluster/installing.go, internal/cluster/insufficient.go, internal/cluster/insufficient_test.go, internal/cluster/mock_cluster_api.go, internal/cluster/ready.go, internal/cluster/ready_test.go, internal/cluster/registrar.go, internal/cluster/registrar_test.go, subsystem/cluster_test.go
=> move deregsiter from step api to register api

internal/hardware/validator.go, internal/hardware/validator_test.go
1. Adding name filter for nvme disks
2. Changing sort from by Name to by smallest size
=> Boot device ordering change:

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/common.go, internal/cluster/installer.go, internal/cluster/installer_test.go, internal/cluster/mock_cluster_api.go, internal/cluster/ready_test.go, subsystem/cluster_test.go
code that was reverted,
including fix for bootstrap selection
=> adding installation to cluster api

Makefile, README.md
=> Remove deploy-for-test from makefile

cmd/main.go, go.mod, go.sum, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/instructionmanager.go, internal/host/instructionmanager_test.go, internal/host/mock_host_api.go, models/host.go, restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/host_test.go, swagger.yaml
@eranco74 @filanov @ronniel1 please review
=>  MGMT-703 - move install logic to getNextStep

internal/host/installcmd.go
Reverts filanov/bm-inventory#118
Doesn't seem to work.
=> Revert "Fixed isntall command"

internal/host/installcmd.go, internal/host/installcmd_test.go
fix install command
@eranco74 @ori-amizur @filanov @tsorya please review
Igal tested it in a real environment and it's working
=> fix install command

.gitignore, Dockerfile.bm-inventory-build, Makefile, tools/create_default_s3_bucket.py, tools/deploy_assisted_installer.py, tools/deploy_assisted_installer_configmap.py, tools/deploy_inventory_service.py, tools/deploy_mariadb.py, tools/deploy_role.py, tools/deploy_s3.py, tools/deploy_scality_configmap.py, tools/utils.py
Replace existing complex Makefile to use python scripts for deployment.
=> Change deployment to python scripts

internal/bminventory/inventory.go
Also fixed the error handling in that function
=> MGMT-854 - Fixed commit after rollback in InstallCluster

go.mod, go.sum, internal/bminventory/inventory.go
temporary adding the full error without filtering, later will filter out only the relevant error message for the user
=> MGMT-808: add reason to all HTTP errors

.github/workflows/image-push.yml, Dockerfile.bm-inventory, Makefile
Getting the label can be done with the following command:
docker inspect <image> | jq .[0].Config.Labels
=> Add git revision to the container's label, instead of a file in the filesystem

Makefile, deploy/bm-inventory-configmap.yaml, deploy/bm-inventory-service.yaml, deploy/bm-inventory.yaml, deploy/mariadb/mariadb-configmap.yaml, deploy/mariadb/mariadb-deployment.yaml, deploy/mariadb/mariadb-storage.yaml, deploy/namespace/namespace.yaml, deploy/roles/role_binding.yaml, deploy/s3/s3-object-expirer-cron.yaml, deploy/s3/scality-configmap.yaml, deploy/s3/scality-deployment.yaml, deploy/s3/scality-storage.yaml, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, tools/clear_deployment.py, tools/deploy_namespace.py, tools/utils.py
Will be pushed with https://github.com/tsorya/test-infra/pull/5
And after i sync with UI team
=> MGMT-761 move deploymnet to assisted-installer-namespace

internal/bminventory/inventory.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/host/connectivitycheckcmd.go, internal/host/connectivitycheckcmd_test.go, internal/host/connectivitycheckconvertor.go, internal/host/connectivitycheckconvertor_test.go, internal/host/disabled_test.go, internal/host/host.go, internal/host/instructionmanager.go, internal/host/mock_host_api.go, models/host.go, restapi/embedded_spec.go, subsystem/host_test.go, swagger.yaml
@ronniel1 @ori-amizur @filanov please review
=> MGMT-796 Implement connectivity check getNextStep

internal/bminventory/inventory.go, internal/cluster/cluster_test.go, internal/cluster/mock_cluster_api.go, internal/events/mock_event.go, internal/hardware/mock_validator.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, models/cluster.go, models/host.go, restapi/embedded_spec.go, swagger.yaml
This without removing the pull_secret entity from the response yet. Currently the UI is relying on it.
Also made the status_updated_at attribute not required
=> MGMT-985 - Added pull_secret_set attribute to cluster

subsystem/cluster_test.go
Ran 21 of 21 Specs in 93.678 seconds
SUCCESS! -- 21 Passed | 0 Failed | 0 Pending | 0 Skipped
=> Use Eventually instead of for loop

subsystem/cluster_test.go
This reverts commit de5577cddf46b0b63e0c501c28de53b0c5e7861c.
=> Revert "Use Eventually instead of for loop"

internal/bminventory/inventory.go, internal/host/hwinfocmd.go
@ronniel1 this change require changing the images to public.
=> Get the agent & hardware_info image from ocpmetal

internal/bminventory/inventory.go, internal/host/hwinfocmd.go
This reverts commit 2da374458802ed20e4f950fceefc1a07c6890dde.
=> Revert "Get the agent & hardware_info image from ocpmetal"

subsystem/cluster_test.go
The test fail in case the node that fail to install is the worker.
Updated the test to fail a master node
=> Fix flaky test, (download_config_files in error state)

internal/bminventory/inventory.go
Instead of doing rollback on every error return the rallback is done in a defer function
=> Change db transaction usage.

Makefile, README.md, tools/deploy_assisted_installer.py, tools/deploy_assisted_installer_configmap.py, tools/deploy_ui.py
All the targets will be taken from ocpmetal quay.io account.
The usage is to add DEPLOY_TAG env to the makefile:
skipper make deploy-all DEPLOY_TAG=stable
For the UI
skipper make deploy-ui DEPLOY_TAG=latest
=> MGMT-1150 Add an option to deplpoy with specific tag

internal/bminventory/inventory.go, internal/host/connectivitycheckcmd.go, internal/host/connectivitycheckcmd_test.go, internal/host/host.go, internal/host/hwinfocmd.go, internal/host/hwinfocmd_test.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/instructionmanager.go, internal/host/instructionmanager_test.go, internal/host/inventorycmd.go, internal/host/inventorycmd_test.go, models/step_reply.go, models/step_type.go, restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/host_test.go, swagger.yaml
Depends on agent being integrated first
=> Ori/mgmt 1145 Move all agent commands to execute only

internal/bminventory/inventory.go, internal/host/connectivitycheckcmd.go, internal/host/connectivitycheckcmd_test.go, internal/host/host.go, internal/host/hwinfocmd.go, internal/host/hwinfocmd_test.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/instructionmanager.go, internal/host/instructionmanager_test.go, internal/host/inventorycmd.go, internal/host/inventorycmd_test.go, models/step_reply.go, models/step_type.go, restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/host_test.go, swagger.yaml
podman does not produce same results as docker
=> Ori/revert mgmt 1145 Revert MGMT-1145 changes

internal/bminventory/inventory.go, internal/host/connectivitycheckcmd.go, internal/host/connectivitycheckcmd_test.go, internal/host/host.go, internal/host/hwinfocmd.go, internal/host/hwinfocmd_test.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/instructionmanager.go, internal/host/instructionmanager_test.go, internal/host/inventorycmd.go, internal/host/inventorycmd_test.go, models/step_reply.go, models/step_type.go, restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/host_test.go, swagger.yaml
=> Re-apply MGMT-1145 Move agent commands to execute only changes

deploy/mariadb/mariadb-storage.yaml, tools/deploy_mariadb.py, tools/utils.py
By default the deployemnt will try to get the current size if exists will use the same size
If not exists 10Gi volume size will be set.
=> MGMT-1244 Change default mariadb volume to 10Gi

internal/bminventory/inventory.go
I set the default values because otherwise the operations will be slower.
=> MGMT-1229 add resources limitation to image generation and kubeconfig generation

subsystem/cluster_test.go
While rebasing cancel installation PR, state info validation was missed
from the subsystem cluster_test. To verify we get the wanted state info
I added the installation and error expected state infos.
=> WIP: MGMT-1311 Subsystem: Fixed state info

Makefile, README.md, deploy/monitoring/grafana/assisted-installer-grafana-dashboard.yaml, deploy/monitoring/grafana/assisted-installer-k8s-grafana.yaml, deploy/monitoring/grafana/assisted-installer-ocp-grafana-route.yaml, deploy/monitoring/grafana/assisted-installer-ocp-grafana.yaml, deploy/monitoring/grafana/grafana-dashboards.yaml, deploy/monitoring/grafana/grafana-k8s.ini, deploy/monitoring/grafana/grafana.ini, deploy/monitoring/grafana/prometheus.json, deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-subscription-instance.yaml, deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-svc.yaml, deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-custom-ca.yaml, deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-route.yaml, deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-subscription-instance.yaml, deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-svc.yaml, deploy/monitoring/prometheus/assisted-installer-operator-group.yaml, deploy/monitoring/prometheus/assisted-installer-operator-subscription.yaml, deploy/monitoring/prometheus/assisted-installer-prometheus-svc-monitor.yaml, tools/deploy_grafana.py, tools/deploy_olm.py, tools/deploy_prometheus.py, tools/utils.py
This PR will include these list of features for development purposes (initially).
=> Add deployment of BM-Inventory Monitoring stack

Makefile
Updated BUILD_FOLDER permission in the swagger-codegen-cli container
=> Fix make create-python-client

subsystem/cluster_test.go, subsystem/image_test.go, subsystem/subsystem_suite_test.go
Use logger in install cluster flows
=> Add logger to subsystem

subsystem/host_test.go
=> MGMT-1188 fix installation_error_reply broken test

internal/bminventory/inventory.go, internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go
Added validation for cluster name format in register/update cluster flows.
=> MGMT-1358: validate cluster name on register and update

Makefile, deploy/bm-inventory-configmap.yaml, tools/deploy_assisted_installer_configmap.py
Set BASE_DNS_DOMAINS in configmap when the env var is defined.
=> configmap: set base_dns_domains from env var

internal/bminventory/inventory.go
s/filesUrl/filesURL - to make go-lint happy
=> inventory: rename filesURL

internal/bminventory/inventory.go
Updateed the restart policy:
Set StartLimitIntervalSec to 0 to disable any kind of rate limiting
Set RestartSec to 3 seconds delay between executions
=> MGMT-1487 Agent might not restart in case of failure

internal/cluster/installer_test.go, internal/cluster/insufficient.go, internal/cluster/insufficient_test.go, internal/host/common.go, internal/host/host.go, internal/host/host_test.go, internal/host/mock_host_api.go, internal/host/resettingpendinguseraction.go, internal/host/resettingpendinguseraction_test.go, internal/host/statemachine.go, internal/host/transition.go, models/host.go, restapi/embedded_spec.go, subsystem/cluster_test.go, swagger.yaml
http://10.0.9.195:8080/job/bm-inventory-subsystem-test/466/console
=> Raz/mgmt 1417-ResettingPendingUserAction

internal/bminventory/inventory.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/instructionmanager.go, internal/versions/versions.go, internal/versions/versions_test.go, subsystem/versions_test.go, tools/deploy_assisted_installer_configmap.py, tools/deployment_options.py
Completing eranco74/assisted-installer#75
=> MGMT-1446 Transfer Controller image flag to the Assisted-Installer

internal/host/host.go
Removed HostStageFinishWaitingForControlPlane
Moved HostStageStartWaitingForControlPlane, to be after HostStageWritingImageToDisk,
=> Updated bootstrap stages

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
http://10.46.10.2:8080/job/bm-inventory-subsystem-test/490/console
=> MGMT-1494 Cancel/Reset: Return host progress stages in response

internal/imgexpirer/imgexpirer.go
Logs:
```
time="2020-07-15T06:24:31Z" level=info msg="Starting bm service" func=main.main file="/home/avishay/work/bm-inventory/cmd/main.go:77"
time="2020-07-15T06:24:32Z" level=info msg="Started Cluster State Monitor" func="github.com/filanov/bm-inventory/pkg/thread.(*Thread).Start" file="/home/avishay/work/bm-inventory/pkg/thread/thread.go:40" pkg=cluster-monitor
time="2020-07-15T06:24:32Z" level=info msg="Started Host State Monitor" func="github.com/filanov/bm-inventory/pkg/thread.(*Thread).Start" file="/home/avishay/work/bm-inventory/pkg/thread/thread.go:40" pkg=host-monitor
time="2020-07-15T06:24:32Z" level=info msg="Started Image Expiration Monitor" func="github.com/filanov/bm-inventory/pkg/thread.(*Thread).Start" file="/home/avishay/work/bm-inventory/pkg/thread/thread.go:40" …
```
=> MGMT-1510: garbage collect dummy ISO immediately

README.md
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> Fix README.md indentation

internal/bminventory/inventory.go, internal/cluster/cluster.go, internal/host/monitor.go
Add request id to creation of dummy image when service go up
=> MGMT-1518 add request id to host and cluster monitors context

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/transition_test.go, internal/host/host.go, internal/host/host_test.go
http://10.46.10.2:8080/job/bm-inventory-subsystem-test/554/console
=> OCPBUGSM-4255 Added reset and cancel to eventsHandler

README.md, deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-svc.yaml, tools/deploy_grafana.py, tools/deploy_prometheus.py
**Aditions:**
- Adding some Pep8 rules
- Fixing Prometheus and Grafana deployment in a non cluster-admin situation
- Added docstrings
=> Fixing PSE deployment and added some adjustments on Prom svc

cmd/main.go, go.mod, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/insufficient.go, internal/cluster/insufficient_test.go, internal/cluster/prepare_test.go, internal/cluster/ready_test.go, internal/cluster/transition_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/transition_test.go, internal/metrics/metricsManager.go, internal/metrics/mock_netricsManager_api.go, subsystem/cluster_test.go, subsystem/host_test.go, subsystem/utils_test.go
I added the missing host & installation finished metrics - I'm sending randon int for installation phase - will fix it after https://issues.redhat.com/browse/MGMT-1564 will be done
@ronniel1 @avishayt please review
=> MGMT-1355 adding host metrics and cluster installation duration

internal/bminventory/inventory.go
We only need to download the docker image to the cluster so there is no reason
to let the dummy job upload anything to s3.
Overwrite the default command into 'echo pass'
=> MGMT-1603 Prevent dummy iso generation uploading to s3

models/host_stage.go, restapi/embedded_spec.go, swagger.yaml
I'll remove the "Start Waiting for control plane" once assisted installer is using the new stage
=> Added "Waiting for control plane" to host stages

internal/bminventory/inventory.go
https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/release.txt
It contains etcd fix for 1st nic
=> MGMT-1607 Upgrade bm-inventory to install 4.5.3 OCP

subsystem/cluster_test.go
"cancel_failed_cluster" test is starting installation, then failing it, then
trying to abort the installation. 
Since host monitor is now setting all hosts to error in case cluster is in
error, on some cases it get race condition when subsystem and monitor try to
set the host state at the same time. I fixed it by canceling the installation
only after hosts monitor set the hosts states to error.
=> MGMT-1632 Subsystem: fixed "cancel_failed_cluster" test

.github/workflows/image-push.yml, Dockerfile.bm-inventory
This reverts commit 964c3cd9a20b524fb10808d198b20c83686adf7e.
=> Revert "Publish image with PR_{hash} tag for any PR build"

tools/deploy_ui.py
Try to pull ui image locally before using it to create deployment configuration.
=> OCPBUGSM-10683 Deploy UI: pull image

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/statemachine.go, internal/cluster/transition_test.go, internal/host/statemachine.go, internal/host/transition_test.go, subsystem/cluster_test.go
Allow canceling or resetting installation from preparing-for-installation
state. Added subsystem-test.
=> MGMT-1582 Cancel/Reset from preparing-for-installation
