swagger.yaml

As we discussed in the daily, force the user to set the openshiftVersion upon cluster create.  After that it cannot be changed.  This is to allow starting the download of the ISO earlier in the process.

swagger: openshiftVersion set only upon cluster create

---

internal/bminventory/inventory.go

Latest assisted-installer image uses the bm-inventory client for fetching the files so there is no need to pass the s3 params
Instead we need to pass the host and port of the bm-inventory service.
Mote that this PR should be merged only after this [PR](https://github.com/eranco74/assisted-installer/pull/10)

Update assisted-installer to latest image

---

internal/host/installcmd.go

Map network to host so localhost will get to the kubeapi server running on the actual host

MGMT-841 Assisted installer should use kubeconfig-loopback

---

Dockerfile.s3-object-expirer
Makefile
deploy/s3/s3-object-expirer-cron.yaml
skipper.yaml
tools/expirer.py

Adds a k8s CronJob that lists the objects in the S3 bucket that we use
for storing ISOs and deletes any that are older than 1 day. This is
because Scality does not support bucket lifecycle policies for
expiration. Deployments running in AWS shouldn't use this.
The expirer script has some environment variables that aren't passed
automatically. The defaults are currently suitable for our tests and can
be overidden in other deployments.

MGMT-848: Clean up ISOs that are older than a day

---

cmd/main.go

It doesn't work if the variable starts with a lower-case letter,
resulting in an interval of 0s instead of the desired 10s. This causes
zero waiting between consecutive calls which is not what we want.

Fix envconfig parsing for ClusterStateMonitorInterval

---

internal/hardware/validator.go
internal/host/instructionmanager.go
internal/host/instructionmanager_test.go

Made the insuficient status info a little more clear

HW inventory steps should be sent to hosts in insuficient state.

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/installing.go
internal/cluster/mock_cluster_api.go
internal/events/mock_event.go
internal/hardware/mock_validator.go
internal/host/host.go
internal/host/mock_host_api.go
internal/host/mock_instruction_api.go

We still have two places related to cluster update and download image. 
but it's less urgent so it will be fixed in a different PR
This is the fix:
```
if err := tx.Model(&host).Update("checked_in_at", host.CheckedInAt).Error; err != nil {
```

Fix db transaction race

---

deploy/s3/s3-object-expirer-cron.yaml
tools/expirer.py

Delete ISOs from S3 that are older than 1 hour rather than 1 day.
Also clean up old pods from the CronJob.

MGMT-998: Clean ISOs older than 1 hour

---

deploy/bm-inventory-service.yaml
deploy/roles/default_role.yaml

Those changes are necesary in order to add the monitoring part on the Minikube side.
After these ones, you need to follow this steps:
- Deploy OLM
- Deploy Prometheus operator
- Deploy Prometheus instance
- Create the service of the Assisted Installer for Prometheus
- Create the ServiceMonitor
With that you will be able to see the monitoring screen on your cluster using a port-forward

Preparing the Role and service to be fully compatible with Prometheus monitoring

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/mock_cluster_api.go

MGMT-1038 prevent update while cluster is installing

Osher/mgmt 1038 - Should not allow to update hosts when the installation has started

---

tools/debug/s3-list-cron.yaml

Useful for debugging the s3 object expiration, the job runs every 15
minutes and you can see the list of objects in the pod's log.

CronJob to periodically list objects in S3

---

internal/bminventory/inventory.go

Tested with Fedora Live ISO
```
$ cat /etc/redhat-release 
Fedora release 31 (Thirty One)
$ systemctl status agent
● agent.service
Loaded: loaded (/etc/systemd/system/agent.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2020-06-17 06:14:00 UTC; 7min ago
Process: 965 ExecStartPre=/usr/bin/podman run --privileged --rm -v /usr/local/bin:/hostbin quay.io/ocpmetal/agent:stable cp /usr/bin/agent /hostbin (code=exited, status=0>
Main PID: 1361 (agent)
Tasks: 10 (limit: 18963)
Memory: 357.3M
CGroup: /system.slice/agent.service
└─1361 /usr/local/bin/agent --host 10.46.9.255 --port 6000 --cluster-id dd243093-99fc-461a-922d-3d6fc2161057
```

MGMT-1115 Run Agent service with podman

---

deploy/bm-inventory.yaml
deploy/mariadb/mariadb-deployment.yaml
deploy/s3/s3-object-expirer-cron.yaml

I added the limits by the status that we currently have in the demo cluster. 
The limit is more then twice bigger then the current state because right now we have a small amount of clusters. 
I didn't tested the environment with a large amount of clusters, so we may adjust the settings later.

MGMT-900 Add resource limitations to bm-inventory, mariadb

---

internal/common/db.go

Source: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9760/rehearse-9760-pull-ci-openshift-installer-release-4.5-e2e-metal-assisted/1275360525860999168
```bash
skipper make _deploy_nodes ADDITIONAL_PARAMS=-in -i
[skipper] Using build container: test-infra:latest
*** PULL_SECRET ***
2020-06-23 09:58:14,189 INFO       Getting inventory URL 	(/opt/dev-scripts/test-infra/discovery-infra/utils.py:40)
2020-06-23 09:58:14,276 INFO       Inventory URL http://192.168.39.36:30192 	(/opt/dev-scripts/test-infra/discovery-infra/bm_inventory_api.py:133)
*** PULL_SECRET ***
Traceback (most recent call last):
File "discovery-infra/start_discovery.py", line 231, in <module>
main()
File "discovery-infra/start_discovery.py", line 186, in main …
```

Enlarging pull secret size to support Prow

---

deploy/s3/s3-object-expirer-cron.yaml
internal/bminventory/inventory.go

We delete all successful jobs, keep the latest failed job. Also made the
error message clearer for 404 when downloading an ISO.

MGMT-1240: Cleanup old s3-expirer jobs

---

Makefile
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Add FOR UPDATE query option to handle race between the update and host monitor
in update cluster
FOR UPDATE is not supported in sqlite3 (unit tests) so testMode flag is added to the inventory to disable this option if we are running in test mode.
There are multiple conditions that require host status refresh to make sure we cover all of them i refresh host status on every update operation.

Refresh host status on every cluster update operation

---

Dockerfile.bm-inventory
deploy/bm-inventory-configmap.yaml
deploy/bm-inventory.yaml
go.mod
go.sum
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

As part of cluster installation flow, base DNS domain
has to be specified by the user. When using a supported
DNS domain [1], requests for adding relevant record sets
are invoked using a dns-client [2]. For now, supporting
AWS Route 53 service.
The following record sets (of type A) should be registered:
- api.cluster-name.domain-name -> API Virtual IP
- *.apps.cluster-name.domain-name -> Ingress Virtual IP
Affected flows:
- Cluster installation: create DNS record sets.
- Cluster deregister: cleanup (remove the record sets).
Usage requirements:
- Create 'route53-creds' secret from the /.aws/credentials file:
$ oc -n assisted-installer create secret generic route53-creds \
--from-file=/root/.aws/credentials
- Add the base domain (name/id/type) to bm-inventory-configmap file.
Not included in …

MGMT-1101: introduce Route 53 DNS service support

---

Makefile
deploy/route53/route53-secret.yaml
tools/deploy_route53.py

* Added 'deploy_route53.py' to tools:
- for creating route53 secret using 'route53-secret.yaml' template,
with secret value specified on ROUTE53_SECRET env var.
* Added deploy-route53 rule to Makefile - invoked from deploy-all

deploy: handle route53 secret creation

---

README.md
deploy/monitoring/grafana/assisted-installer-k8s-grafana.yaml
deploy/monitoring/grafana/assisted-installer-ocp-grafana.yaml
deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-svc.yaml
deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-svc.yaml

Fixed:
- Prometheus SVC on OCP to assisted installer namespace
- Prometheus SVC on K8s to assisted installer namespace
- Grafana SVC on OCP to assisted installer namespace
- Grafana SVC on K8s to assisted installer namespace
Added:
- Documentation about how to expose the metrics on your local deployment

Fixing #320, wrong NS deploying monitoring services

---

Makefile
README.md
tools/deploy_assisted_installer.py
tools/deploy_assisted_installer_configmap.py
tools/deploy_s3_object_expirer.py
tools/deploy_ui.py
tools/deployment_options.py
tools/utils.py

Usage:
Deploy images according to the manifest:
```
skipper make deploy-all DEPLOY_MANIFEST_PATH=./assisted-installer.yaml
```
Deploy images according to the manifest in the assisted-installer-deployment repo (require git tag/branch/hash):
```
skipper make deploy-all DEPLOY_MANIFEST_TAG=master
```
Deploy all the images with the same specified:
```
skipper make deploy-all DEPLOY_TAG=v7.7.7
```
Default remain `latest`
You can still override default using ENV VAR
```
skipper make deploy-all SERVICE=quay.io/mySpecialImage:latest
```

Support deploy manifest in bm-inventory deployment scripts

---

internal/bminventory/inventory.go
internal/host/common.go
internal/host/disabled.go
internal/host/disabled_test.go
internal/host/disconnected.go
internal/host/disconnected_test.go
internal/host/discovering.go
internal/host/discovering_test.go
internal/host/error.go
internal/host/error_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/installed.go
internal/host/installed_test.go
internal/host/installing.go
internal/host/installing_test.go
internal/host/insufficient.go
internal/host/insufficient_test.go
internal/host/known.go
internal/host/known_test.go
internal/host/mock_host_api.go
internal/host/resetting.go
internal/host/resetting_test.go

Update HW info don't affect the state so the only validation is the states that allow getting new hw info, including Disconnected, Discovering, Insufficent and Known

MGMT-1312 move host update hw info from state machine model

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/common.go
internal/cluster/installer.go
internal/cluster/installer_test.go
internal/cluster/mock_cluster_api.go
models/cluster.go
restapi/embedded_spec.go
subsystem/cluster_test.go
swagger.yaml

Cluster install will move cluster to `preparing-for-installation` after some basic validations, the user will get an ok reply, after that the async part of the API will start and move the cluster and the hosts to installing right after the ignition is generated.
If the service will be rebooted then the cluster will be left in `preparing-for-installation` state, handling this issue will solved with https://issues.redhat.com/browse/MGMT-1349

MGMT-1126 make cluster install async

---

Dockerfile.bm-inventory-build
Makefile
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
pkg/s3Client/mock_s3client.go
pkg/s3Client/s3Client.go
tools/expirer.py
tools/expirer_test.py

Together with: https://github.com/oshercc/coreos_installation_iso/pull/9
1. Modify the S3 expirer script to look at the timestamp in the object's
tag rather than it's real timestamp. This is because there's no real
supported way to update an object's timestamp without overwriting it.
2. If the current image exists, has the same parameters, and was created
by the same version that's currently running - update the timestamp
in the tag and return.

MGMT-717: Do not generate image if a valid one already exists

---

internal/cluster/cluster.go
internal/cluster/prepare.go

This is a temp fix - we still need to move cluster api to the new state machine model.

MGMT-1441 add empty implementation to cluster refresh on preparing-for-installation state

---

internal/bminventory/inventory.go

Removed unsed 'clusterNmae' variable from validateBaseDNS and validateDNSRecords funcs.

inventory: remove unused variable

---

tools/wait_for_pod.py

It takes more than 5min (about 7min) for `bm-inventory` pod to get to
a `running` state.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

Extended tools/wait_for_pod.py's timeout.

---

internal/host/transition.go
subsystem/cluster_test.go

Hosts might register after a failed/canceled installation and have old progress
stage and info. Therefore clear these fields in every reset.
Updated reset subsystem-test
http://10.0.9.195:8080/job/bm-inventory-subsystem-test/474/console

MGMT-1488 Host: clear progress fields on register

---

internal/bminventory/inventory.go
internal/host/transition.go
subsystem/cluster_test.go

If the cluster was restarted it probably already contain bootstrap host.
In this case we use the same host, instead of setting a new one.
Also added a verification of this check to the reset subsystem test.
Jenkins build:
http://10.0.9.195:8080/job/bm-inventory-subsystem-test/476/console

MGMT-1424 setBootstrapHost: check if already has bootstrap

---

cmd/main.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/prepare.go
internal/cluster/prepare_test.go
internal/cluster/transition_test.go

Refresh status of this this state will check if cluster status haven't changed for a 10m,
and will push the cluster into error.
This can happen if the service was rebooted or somehow the async part crashed.

MGMT-1349: set timeout to prepare-for-installation status

---

internal/host/statemachine.go
subsystem/cluster_test.go

Inventory should allow cancel/reset installation when some hosts
are disabled. Added transition to statemachine allows that.
Sub-system tests are included.
http://10.46.10.2:8080/job/bm-inventory-subsystem-test/511/

OCPBUGSM-4240 Skip disabled hosts on cancel/reset

---

internal/bminventory/inventory.go

On reset cluster flow, DNS records should be cleaned.
Hence, invoke deleteDNSRecordSets on ResetCluster.

MGMT-1502: remove dns records on cluster reset

---

internal/host/transition.go
subsystem/cluster_test.go

Instead of reusing the same bootstrap without any point,
reset the field on register (in case bootstrap is registered
after reset). Update subsystem-tests
http://10.46.10.2:8080/job/bm-inventory-subsystem-test/516/console

MGMT-1526 Clear bootstrap on register

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
internal/cluster/installing.go
internal/cluster/insufficient.go
internal/cluster/insufficient_test.go
internal/cluster/prepare_test.go
internal/cluster/ready.go

It will prevent races when we get cluster with state A and then because of a race
we can get a cluster with a different state.

MGMT-1565 change cluster refresh status using get cluster from db once

---

client/installer/update_host_install_progress_responses.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/common.go
internal/host/host.go
internal/host/host_test.go
restapi/embedded_spec.go
restapi/operations/installer/update_host_install_progress_responses.go
subsystem/cluster_test.go
swagger.yaml

- Disallowing lower stages (except for "Failed" stage)
- **Behavior change** - `/progress` returns an error in case of an error. The assisted-installer should decide what to do with an error and not to hide it.

MGMT-1490 Enforce stages enum ordering

---

deploy/bm-inventory.yaml
internal/bminventory/inventory.go
tools/deploy_assisted_installer.py

it was used to run a dummy iso generation without pushing it to s3 for testing

MGMT-1594 remove unused ImageBuilderCmd overwrite hack

---

internal/cluster/statemachine.go
internal/cluster/transition_test.go
internal/host/statemachine.go
internal/host/transition_test.go
subsystem/cluster_test.go

We don't really need to set the cluster and host status to error before
cancelling installation. Resetting installing node is just like canceling and
then resetting (cancel cmd just stop podman, but also reset cmd).
Installed nodes will be set to ResettingPendingUserAction.
Update subsystem test to accept the new source states when resetting cluster.
Added unit tests.

MGMT-1231 Reset Installation: allow reset from various states

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/common/host_utils.go
internal/host/common.go
internal/host/common_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/instructionmanager_test.go
internal/host/transition.go
internal/host/transition_test.go

Example from installation:
"message": "Registered cluster",
"message": "Generated image (proxy URL is \"\", SSH public key is set)",
"message": "Started image download",
"message": "Host a234edb4-1e30-4ee5-9e07-17d6f0b338aa: registered to cluster",
"message": "Host da5875f3-c1f6-4ef2-8807-6ff1ab7018f7: registered to cluster",
"message": "Host 93ade469-4a5e-4298-9ba0-88fb0771eecf: registered to cluster",
"message": "Host test-infra-cluster-master-2: updated status from \"discovering\" to \"pending-for-input\" (User input required)",
"message": "Host test-infra-cluster-master-1: updated status from \"discovering\" to \"pending-for-input\" (User input required)",
"message": "Host test-infra-cluster-master-0: updated status from \"discovering\" to \"pending-for-input\" (User input required)", …

MGMT-1402: Add events for all host transitions

---

internal/cluster/installing.go

Instead of
```
Cluster fb1c7d3c-625d-4c63-a492-df12b15a8ca0 hosts status map is map[error:[0xc000a5db00] installing:[0xc000a5dc80 0xc000a5de00]]
```
Looks like
```
Cluster 1d91cf25-16f3-4d95-92d3-503d939cd044 hosts status map is map[error:[7f21d557-1380-45b3-8933-3f553e606888] installed:[064bf9df-bb6c-4ed3-8e8e-1bf289bdbcbd] installing:[b4adfe54-b97c-45fa-8fc9-61c73233af06]]
```

MGMT-1646 clearer monitor log

---

internal/host/statemachine.go
internal/host/transition_test.go
subsystem/cluster_test.go

OPCBUGSM-4299: Allow canceling installed hosts
User may try to cancel an installation where some hosts are already done.
This operation should be permitted.
When it happens, first the hosts states will be changed to error, then after
reset the cluster monitor will set them to resetting-pending-user-action.

OPCBUGSM-4299: Allow canceling installed hosts

---

cmd/main.go
deploy/bm-inventory-configmap.yaml

Bucket creation will be defaulted to "false" and created only on demand.
In integration env we don't have permissions to create buckets so we
can't always create it.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

Updated S3 bucket creation in cmd/main.

---

internal/host/transition_test.go

Previously many of these tests could fail if over three minutes
elapsed between when the array of test cases was defined and when
any individual test was run.
This is because the host `CheckedInAt` time was defined as time.Now()
in the test case definition, not when the test was actually being run.
This was happening in two contexts. One was "All transitions" where
some cases were relying on the check-in time to be out of range (unset)
and others needed it to be within the last 3 minutes. The other was
the "Unique hostname" context where all the tests were using time.Now()
so I removed the test case parameter for that one.
cc @ori-amizur @filanov @ronniel1 
This fixes the problems I was having running the tests locally.

Fix tests which rely on execution under three minutes

---

.gitignore

If this isn't meant to be committed it would be nice to not see it
in `git status`.
Replaces #492 
cc @ronniel1

Add /vendor to .gitignore

---

cmd/main.go
pkg/db/db.go

At this point the pkg contains only a struct grouping all DB fields and
making use of this struct instead of listing all individual fields
separately.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

Created a pkg for DB.
